apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule
  labels:
    app: schedule
spec:
  replicas: 5
  selector:
    matchLabels:
      app: schedule
  template:
    metadata:
      labels:
        app: schedule
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: schedule
          image: 496278789073.dkr.ecr.us-west-2.amazonaws.com/skccuser14-schedule2:v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
